ruby_version: 2.5

format: progress

ignore:
  - '**/*':
    - Standard/SemanticBlocks
    - Performance/RegexpMatch
    - Layout/EmptyLineAfterGuardClause
    - Layout/EmptyLinesAfterModuleInclusion
  - 'spec/**/*':
    - Lint/UselessAssignment
    - Lint/Void
