source "https://rubygems.org"

gemspec

# Exclude development-only gems from dependabot.
unless ENV["DEPENDABOT"]
  gem "irb"
  gem "timecop"

  gem "rake"
  gem "rspec", "~> 3.11"

  # Exclude development-only gems from the gemfiles generated by appraisal.
  unless defined?(::Appraisal::Gemfile) && is_a?(::Appraisal::Gemfile)
    gem "appraisal", require: false
    gem "standard", require: false
    gem "simplecov", require: false
    gem "yard", require: false

    group :development do
      gem "ruby-prof", require: false, platforms: [:mri]
      gem "memory_profiler", require: false, platforms: [:mri]
    end
  end
end
