name: Continuous Integration
on:
  push:
    branches:
      - master
      - actions-*
    tags:
      - v*
  pull_request:
env:
  BUNDLE_CLEAN: "true"
  BUNDLE_PATH: vendor/bundle
  BUNDLE_JOBS: 3
  BUNDLE_RETRY: 3
jobs:
  specs:
    name: ${{ matrix.job }} ruby-${{ matrix.ruby }} ${{ matrix.appraisal }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ "2.3", "2.4", "2.5", "2.6", "2.7", "3.0", "3", "jruby" ]
        job: [ rspec ]
        include:
          - ruby: "ruby"
            stanardrb: true
          - ruby: "jruby"
          - ruby: "3"
          - ruby: "3.0"
          - ruby: "2.7"
          - ruby: "2.6"
          - ruby: "2.5"
          - ruby: "2.4"
          - ruby: "2.3"
          - ruby: "2.5"
            appraisal: activesupport_4
            bundler: "1.17.3"
          - ruby: "2.5"
            appraisal: activesupport_5
          - ruby: "2.6"
            appraisal: activesupport
          - ruby: "2.6"
            appraisal: logger
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Setup bundler
        if: matrix.bundler != ''
        run: |
          gem uninstall bundler --all
          gem install bundler --no-document --version ${{ matrix.bundler }}
      - name: Set Appraisal bundle
        if: matrix.appraisal != ''
        run: |
          echo "using gemfile gemfiles/${{ matrix.appraisal }}.gemfile"
          bundle config set gemfile "gemfiles/${{ matrix.appraisal }}.gemfile"
          fi
      - name: Install bundle
        run: |
          bundle update
      - name: Run specs
        if:   matrix.job == 'rspec'
        run:  bundle exec rake spec
      - name: Run standardrb
        if:   matrix.standardrb == true
        run:  bundle exec standardrb
