name: Regression Test
on:
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * 1"
env:
  BUNDLE_CLEAN: "true"
  BUNDLE_PATH: vendor/bundle
  BUNDLE_JOBS: 3
  BUNDLE_RETRY: 3
jobs:
  specs:
    name: Run specs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
      - name: Install bundler
        run: |
          bundle update
      - name: Run specs
        run: |
          bundle exec rake spec
